// Copyright 2023 LiveKit, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: ipc.proto

package ipc

import (
	livekit "github.com/livekit/protocol/livekit"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateIngressStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Info          *livekit.IngressInfo   `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateIngressStateRequest) Reset() {
	*x = UpdateIngressStateRequest{}
	mi := &file_ipc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIngressStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIngressStateRequest) ProtoMessage() {}

func (x *UpdateIngressStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIngressStateRequest.ProtoReflect.Descriptor instead.
func (*UpdateIngressStateRequest) Descriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateIngressStateRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *UpdateIngressStateRequest) GetInfo() *livekit.IngressInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type GstPipelineDebugDotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GstPipelineDebugDotRequest) Reset() {
	*x = GstPipelineDebugDotRequest{}
	mi := &file_ipc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GstPipelineDebugDotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GstPipelineDebugDotRequest) ProtoMessage() {}

func (x *GstPipelineDebugDotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GstPipelineDebugDotRequest.ProtoReflect.Descriptor instead.
func (*GstPipelineDebugDotRequest) Descriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{1}
}

type GstPipelineDebugDotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DotFile       string                 `protobuf:"bytes,1,opt,name=dot_file,json=dotFile,proto3" json:"dot_file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GstPipelineDebugDotResponse) Reset() {
	*x = GstPipelineDebugDotResponse{}
	mi := &file_ipc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GstPipelineDebugDotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GstPipelineDebugDotResponse) ProtoMessage() {}

func (x *GstPipelineDebugDotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GstPipelineDebugDotResponse.ProtoReflect.Descriptor instead.
func (*GstPipelineDebugDotResponse) Descriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{2}
}

func (x *GstPipelineDebugDotResponse) GetDotFile() string {
	if x != nil {
		return x.DotFile
	}
	return ""
}

type PProfRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileName   string                 `protobuf:"bytes,1,opt,name=profile_name,json=profileName,proto3" json:"profile_name,omitempty"`
	Timeout       int32                  `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Debug         int32                  `protobuf:"varint,3,opt,name=debug,proto3" json:"debug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PProfRequest) Reset() {
	*x = PProfRequest{}
	mi := &file_ipc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PProfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PProfRequest) ProtoMessage() {}

func (x *PProfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PProfRequest.ProtoReflect.Descriptor instead.
func (*PProfRequest) Descriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{3}
}

func (x *PProfRequest) GetProfileName() string {
	if x != nil {
		return x.ProfileName
	}
	return ""
}

func (x *PProfRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *PProfRequest) GetDebug() int32 {
	if x != nil {
		return x.Debug
	}
	return 0
}

type PProfResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PprofFile     []byte                 `protobuf:"bytes,1,opt,name=pprof_file,json=pprofFile,proto3" json:"pprof_file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PProfResponse) Reset() {
	*x = PProfResponse{}
	mi := &file_ipc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PProfResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PProfResponse) ProtoMessage() {}

func (x *PProfResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PProfResponse.ProtoReflect.Descriptor instead.
func (*PProfResponse) Descriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{4}
}

func (x *PProfResponse) GetPprofFile() []byte {
	if x != nil {
		return x.PprofFile
	}
	return nil
}

type GatherMediaStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatherMediaStatsRequest) Reset() {
	*x = GatherMediaStatsRequest{}
	mi := &file_ipc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatherMediaStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatherMediaStatsRequest) ProtoMessage() {}

func (x *GatherMediaStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatherMediaStatsRequest.ProtoReflect.Descriptor instead.
func (*GatherMediaStatsRequest) Descriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{5}
}

type GatherMediaStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *MediaStats            `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatherMediaStatsResponse) Reset() {
	*x = GatherMediaStatsResponse{}
	mi := &file_ipc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatherMediaStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatherMediaStatsResponse) ProtoMessage() {}

func (x *GatherMediaStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatherMediaStatsResponse.ProtoReflect.Descriptor instead.
func (*GatherMediaStatsResponse) Descriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{6}
}

func (x *GatherMediaStatsResponse) GetStats() *MediaStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type UpdateMediaStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *MediaStats            `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMediaStatsRequest) Reset() {
	*x = UpdateMediaStatsRequest{}
	mi := &file_ipc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMediaStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMediaStatsRequest) ProtoMessage() {}

func (x *UpdateMediaStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMediaStatsRequest.ProtoReflect.Descriptor instead.
func (*UpdateMediaStatsRequest) Descriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateMediaStatsRequest) GetStats() *MediaStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type MediaStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackStats    map[string]*TrackStats `protobuf:"bytes,1,rep,name=track_stats,json=trackStats,proto3" json:"track_stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaStats) Reset() {
	*x = MediaStats{}
	mi := &file_ipc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaStats) ProtoMessage() {}

func (x *MediaStats) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaStats.ProtoReflect.Descriptor instead.
func (*MediaStats) Descriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{8}
}

func (x *MediaStats) GetTrackStats() map[string]*TrackStats {
	if x != nil {
		return x.TrackStats
	}
	return nil
}

type TrackStats struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	AverageBitrate       uint32                 `protobuf:"varint,1,opt,name=average_bitrate,json=averageBitrate,proto3" json:"average_bitrate,omitempty"`
	CurrentBitrate       uint32                 `protobuf:"varint,2,opt,name=current_bitrate,json=currentBitrate,proto3" json:"current_bitrate,omitempty"`
	TotalPackets         uint64                 `protobuf:"varint,4,opt,name=total_packets,json=totalPackets,proto3" json:"total_packets,omitempty"`
	CurrentPackets       uint64                 `protobuf:"varint,5,opt,name=current_packets,json=currentPackets,proto3" json:"current_packets,omitempty"`
	TotalLossRate        float64                `protobuf:"fixed64,6,opt,name=total_loss_rate,json=totalLossRate,proto3" json:"total_loss_rate,omitempty"`
	CurrentLossRate      float64                `protobuf:"fixed64,7,opt,name=current_loss_rate,json=currentLossRate,proto3" json:"current_loss_rate,omitempty"`
	TotalPli             uint64                 `protobuf:"varint,8,opt,name=total_pli,json=totalPli,proto3" json:"total_pli,omitempty"`
	CurrentPli           uint64                 `protobuf:"varint,9,opt,name=current_pli,json=currentPli,proto3" json:"current_pli,omitempty"`
	Jitter               *JitterStats           `protobuf:"bytes,10,opt,name=jitter,proto3" json:"jitter,omitempty"`
	PacketLatencySeconds []float64              `protobuf:"fixed64,11,rep,packed,name=packet_latency_seconds,json=packetLatencySeconds,proto3" json:"packet_latency_seconds,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TrackStats) Reset() {
	*x = TrackStats{}
	mi := &file_ipc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackStats) ProtoMessage() {}

func (x *TrackStats) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackStats.ProtoReflect.Descriptor instead.
func (*TrackStats) Descriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{9}
}

func (x *TrackStats) GetAverageBitrate() uint32 {
	if x != nil {
		return x.AverageBitrate
	}
	return 0
}

func (x *TrackStats) GetCurrentBitrate() uint32 {
	if x != nil {
		return x.CurrentBitrate
	}
	return 0
}

func (x *TrackStats) GetTotalPackets() uint64 {
	if x != nil {
		return x.TotalPackets
	}
	return 0
}

func (x *TrackStats) GetCurrentPackets() uint64 {
	if x != nil {
		return x.CurrentPackets
	}
	return 0
}

func (x *TrackStats) GetTotalLossRate() float64 {
	if x != nil {
		return x.TotalLossRate
	}
	return 0
}

func (x *TrackStats) GetCurrentLossRate() float64 {
	if x != nil {
		return x.CurrentLossRate
	}
	return 0
}

func (x *TrackStats) GetTotalPli() uint64 {
	if x != nil {
		return x.TotalPli
	}
	return 0
}

func (x *TrackStats) GetCurrentPli() uint64 {
	if x != nil {
		return x.CurrentPli
	}
	return 0
}

func (x *TrackStats) GetJitter() *JitterStats {
	if x != nil {
		return x.Jitter
	}
	return nil
}

func (x *TrackStats) GetPacketLatencySeconds() []float64 {
	if x != nil {
		return x.PacketLatencySeconds
	}
	return nil
}

type JitterStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	P50           float64                `protobuf:"fixed64,1,opt,name=p50,proto3" json:"p50,omitempty"` // in ms
	P90           float64                `protobuf:"fixed64,2,opt,name=p90,proto3" json:"p90,omitempty"`
	P99           float64                `protobuf:"fixed64,3,opt,name=p99,proto3" json:"p99,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JitterStats) Reset() {
	*x = JitterStats{}
	mi := &file_ipc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JitterStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JitterStats) ProtoMessage() {}

func (x *JitterStats) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JitterStats.ProtoReflect.Descriptor instead.
func (*JitterStats) Descriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{10}
}

func (x *JitterStats) GetP50() float64 {
	if x != nil {
		return x.P50
	}
	return 0
}

func (x *JitterStats) GetP90() float64 {
	if x != nil {
		return x.P90
	}
	return 0
}

func (x *JitterStats) GetP99() float64 {
	if x != nil {
		return x.P99
	}
	return 0
}

type KillIngressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillIngressRequest) Reset() {
	*x = KillIngressRequest{}
	mi := &file_ipc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillIngressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillIngressRequest) ProtoMessage() {}

func (x *KillIngressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillIngressRequest.ProtoReflect.Descriptor instead.
func (*KillIngressRequest) Descriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{11}
}

type KillIngressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *livekit.IngressState  `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillIngressResponse) Reset() {
	*x = KillIngressResponse{}
	mi := &file_ipc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillIngressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillIngressResponse) ProtoMessage() {}

func (x *KillIngressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillIngressResponse.ProtoReflect.Descriptor instead.
func (*KillIngressResponse) Descriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{12}
}

func (x *KillIngressResponse) GetState() *livekit.IngressState {
	if x != nil {
		return x.State
	}
	return nil
}

var File_ipc_proto protoreflect.FileDescriptor

const file_ipc_proto_rawDesc = "" +
	"\n" +
	"\tipc.proto\x12\x03ipc\x1a\x1bgoogle/protobuf/empty.proto\x1a\x15livekit_ingress.proto\"d\n" +
	"\x19UpdateIngressStateRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12(\n" +
	"\x04info\x18\x02 \x01(\v2\x14.livekit.IngressInfoR\x04info\"\x1c\n" +
	"\x1aGstPipelineDebugDotRequest\"8\n" +
	"\x1bGstPipelineDebugDotResponse\x12\x19\n" +
	"\bdot_file\x18\x01 \x01(\tR\adotFile\"a\n" +
	"\fPProfRequest\x12!\n" +
	"\fprofile_name\x18\x01 \x01(\tR\vprofileName\x12\x18\n" +
	"\atimeout\x18\x02 \x01(\x05R\atimeout\x12\x14\n" +
	"\x05debug\x18\x03 \x01(\x05R\x05debug\".\n" +
	"\rPProfResponse\x12\x1d\n" +
	"\n" +
	"pprof_file\x18\x01 \x01(\fR\tpprofFile\"\x19\n" +
	"\x17GatherMediaStatsRequest\"A\n" +
	"\x18GatherMediaStatsResponse\x12%\n" +
	"\x05stats\x18\x01 \x01(\v2\x0f.ipc.MediaStatsR\x05stats\"@\n" +
	"\x17UpdateMediaStatsRequest\x12%\n" +
	"\x05stats\x18\x01 \x01(\v2\x0f.ipc.MediaStatsR\x05stats\"\x9e\x01\n" +
	"\n" +
	"MediaStats\x12@\n" +
	"\vtrack_stats\x18\x01 \x03(\v2\x1f.ipc.MediaStats.TrackStatsEntryR\n" +
	"trackStats\x1aN\n" +
	"\x0fTrackStatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.ipc.TrackStatsR\x05value:\x028\x01\"\x9e\x03\n" +
	"\n" +
	"TrackStats\x12'\n" +
	"\x0faverage_bitrate\x18\x01 \x01(\rR\x0eaverageBitrate\x12'\n" +
	"\x0fcurrent_bitrate\x18\x02 \x01(\rR\x0ecurrentBitrate\x12#\n" +
	"\rtotal_packets\x18\x04 \x01(\x04R\ftotalPackets\x12'\n" +
	"\x0fcurrent_packets\x18\x05 \x01(\x04R\x0ecurrentPackets\x12&\n" +
	"\x0ftotal_loss_rate\x18\x06 \x01(\x01R\rtotalLossRate\x12*\n" +
	"\x11current_loss_rate\x18\a \x01(\x01R\x0fcurrentLossRate\x12\x1b\n" +
	"\ttotal_pli\x18\b \x01(\x04R\btotalPli\x12\x1f\n" +
	"\vcurrent_pli\x18\t \x01(\x04R\n" +
	"currentPli\x12(\n" +
	"\x06jitter\x18\n" +
	" \x01(\v2\x10.ipc.JitterStatsR\x06jitter\x124\n" +
	"\x16packet_latency_seconds\x18\v \x03(\x01R\x14packetLatencySeconds\"C\n" +
	"\vJitterStats\x12\x10\n" +
	"\x03p50\x18\x01 \x01(\x01R\x03p50\x12\x10\n" +
	"\x03p90\x18\x02 \x01(\x01R\x03p90\x12\x10\n" +
	"\x03p99\x18\x03 \x01(\x01R\x03p99\"\x14\n" +
	"\x12KillIngressRequest\"B\n" +
	"\x13KillIngressResponse\x12+\n" +
	"\x05state\x18\x01 \x01(\v2\x15.livekit.IngressStateR\x05state2^\n" +
	"\x0eIngressService\x12L\n" +
	"\x12UpdateIngressState\x12\x1e.ipc.UpdateIngressStateRequest\x1a\x16.google.protobuf.Empty2\xff\x02\n" +
	"\x0eIngressHandler\x12U\n" +
	"\x0eGetPipelineDot\x12\x1f.ipc.GstPipelineDebugDotRequest\x1a .ipc.GstPipelineDebugDotResponse\"\x00\x123\n" +
	"\bGetPProf\x12\x11.ipc.PProfRequest\x1a\x12.ipc.PProfResponse\"\x00\x12Q\n" +
	"\x10GatherMediaStats\x12\x1c.ipc.GatherMediaStatsRequest\x1a\x1d.ipc.GatherMediaStatsResponse\"\x00\x12J\n" +
	"\x10UpdateMediaStats\x12\x1c.ipc.UpdateMediaStatsRequest\x1a\x16.google.protobuf.Empty\"\x00\x12B\n" +
	"\vKillIngress\x12\x17.ipc.KillIngressRequest\x1a\x18.ipc.KillIngressResponse\"\x00B$Z\"github.com/livekit/ingress/pkg/ipcb\x06proto3"

var (
	file_ipc_proto_rawDescOnce sync.Once
	file_ipc_proto_rawDescData []byte
)

func file_ipc_proto_rawDescGZIP() []byte {
	file_ipc_proto_rawDescOnce.Do(func() {
		file_ipc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ipc_proto_rawDesc), len(file_ipc_proto_rawDesc)))
	})
	return file_ipc_proto_rawDescData
}

var file_ipc_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_ipc_proto_goTypes = []any{
	(*UpdateIngressStateRequest)(nil),   // 0: ipc.UpdateIngressStateRequest
	(*GstPipelineDebugDotRequest)(nil),  // 1: ipc.GstPipelineDebugDotRequest
	(*GstPipelineDebugDotResponse)(nil), // 2: ipc.GstPipelineDebugDotResponse
	(*PProfRequest)(nil),                // 3: ipc.PProfRequest
	(*PProfResponse)(nil),               // 4: ipc.PProfResponse
	(*GatherMediaStatsRequest)(nil),     // 5: ipc.GatherMediaStatsRequest
	(*GatherMediaStatsResponse)(nil),    // 6: ipc.GatherMediaStatsResponse
	(*UpdateMediaStatsRequest)(nil),     // 7: ipc.UpdateMediaStatsRequest
	(*MediaStats)(nil),                  // 8: ipc.MediaStats
	(*TrackStats)(nil),                  // 9: ipc.TrackStats
	(*JitterStats)(nil),                 // 10: ipc.JitterStats
	(*KillIngressRequest)(nil),          // 11: ipc.KillIngressRequest
	(*KillIngressResponse)(nil),         // 12: ipc.KillIngressResponse
	nil,                                 // 13: ipc.MediaStats.TrackStatsEntry
	(*livekit.IngressInfo)(nil),         // 14: livekit.IngressInfo
	(*livekit.IngressState)(nil),        // 15: livekit.IngressState
	(*emptypb.Empty)(nil),               // 16: google.protobuf.Empty
}
var file_ipc_proto_depIdxs = []int32{
	14, // 0: ipc.UpdateIngressStateRequest.info:type_name -> livekit.IngressInfo
	8,  // 1: ipc.GatherMediaStatsResponse.stats:type_name -> ipc.MediaStats
	8,  // 2: ipc.UpdateMediaStatsRequest.stats:type_name -> ipc.MediaStats
	13, // 3: ipc.MediaStats.track_stats:type_name -> ipc.MediaStats.TrackStatsEntry
	10, // 4: ipc.TrackStats.jitter:type_name -> ipc.JitterStats
	15, // 5: ipc.KillIngressResponse.state:type_name -> livekit.IngressState
	9,  // 6: ipc.MediaStats.TrackStatsEntry.value:type_name -> ipc.TrackStats
	0,  // 7: ipc.IngressService.UpdateIngressState:input_type -> ipc.UpdateIngressStateRequest
	1,  // 8: ipc.IngressHandler.GetPipelineDot:input_type -> ipc.GstPipelineDebugDotRequest
	3,  // 9: ipc.IngressHandler.GetPProf:input_type -> ipc.PProfRequest
	5,  // 10: ipc.IngressHandler.GatherMediaStats:input_type -> ipc.GatherMediaStatsRequest
	7,  // 11: ipc.IngressHandler.UpdateMediaStats:input_type -> ipc.UpdateMediaStatsRequest
	11, // 12: ipc.IngressHandler.KillIngress:input_type -> ipc.KillIngressRequest
	16, // 13: ipc.IngressService.UpdateIngressState:output_type -> google.protobuf.Empty
	2,  // 14: ipc.IngressHandler.GetPipelineDot:output_type -> ipc.GstPipelineDebugDotResponse
	4,  // 15: ipc.IngressHandler.GetPProf:output_type -> ipc.PProfResponse
	6,  // 16: ipc.IngressHandler.GatherMediaStats:output_type -> ipc.GatherMediaStatsResponse
	16, // 17: ipc.IngressHandler.UpdateMediaStats:output_type -> google.protobuf.Empty
	12, // 18: ipc.IngressHandler.KillIngress:output_type -> ipc.KillIngressResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_ipc_proto_init() }
func file_ipc_proto_init() {
	if File_ipc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ipc_proto_rawDesc), len(file_ipc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_ipc_proto_goTypes,
		DependencyIndexes: file_ipc_proto_depIdxs,
		MessageInfos:      file_ipc_proto_msgTypes,
	}.Build()
	File_ipc_proto = out.File
	file_ipc_proto_goTypes = nil
	file_ipc_proto_depIdxs = nil
}
